package on2016_05.on2016_05_09_May_Challenge_2016.Chef_and_Amazingness_of_Numbers;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("io/test/on2016_05/on2016_05_09_May_Challenge_2016/Chef_and_Amazingness_of_Numbers/Chef and Amazingness of IntegerUtils.task"))
			Assert.fail();
	}
}
